LAB5
tronyaginaa/computer_graphics pull request #5
Opened 2024-03-15 14:38 UTC by tronyaginaa

2024-03-17 19:08 UTC, maloxit requested changes
Надо поправить:
- Debug layer пишет о не освобождённых объектах
- С одной из сторон один треугольник полностью перекрывает другой. Надо добавить сортировку по глубине для прозрачных объектов
- Текстуры надо сжать с mip уровнями (можно использовать compressonator например)

2024-03-18 22:46 UTC, maloxit requested changes
Зачту с плюсом, но есть замечания, которые надо поправить:
- Где-то потеряли файлы в последних коммитах, как минимум renderer.h и текстуру. Ещё надо поправить имена в постбилд команде копирования
- Треугольники теперь не перекрывают друг-друга по depth буферу, но всё ещё выводятся в неправильном порядке. Надо добавить сортировку (хотя бы просто по расстоянию до камеры

2024-03-24 23:02 UTC, tronyaginaa commented
Добавила сортировку и незакоммиченные файлы

2024-03-25 23:22 UTC, maloxit approved these changes
Зачел

2024-03-29 16:01 UTC, merged